myname: 
  name: abc
  servers: 
    - dev.bar.com
    - foo.bar.com
  mappingMap: 
    person1: 
      name: aaa
      addresses: 
        na: jiang
        sb: su
    person2: 
      name: bbb
      addresses: 
        to: jiang
        bit: su
