prefix:
    stringProp1: propValue1
    stringProp2: propValue2
    intProp1: 10
    listProp:
        - listValue1
        - listValue2
    mapProp: 
      Entity1: 
        mappingMap: 
          postalNo: PostalNo
          postalCode: PostalCode
           
myname: 
  name: abc
  servers: 
    - dev.bar.com
    - foo.bar.com
  mappingMap: 
    postalNo: PostalNo
    postalCode: PostalCode
