myname: 
  name: abc
  servers: 
    - dev.bar.com
    - foo.bar.com
  mappingMap: 
    "[o.s.b.a.e.mvc.EndpointHandlerMapping]": 
      name: o.s.b.a.e.mvc.End
      addresses: 
        na: jiang
        sb: su
    "[aaaaaaao.s.b.a.e.mvc.EndpointHandlerMapping]": 
      name: aaaaaaao.s.b.a.e.mvc.End
      addresses: 
        to: jiang
        bit: su
