prefix:
    stringProp1: propValue1custom
    stringProp2: propValue2
    intProp1: 10
    listProp:
        - listValue1
        - listValue2
    mapProp: 
      Entity1: 
        mappingMap: 
          postalNo: PostalNo
          postalCode: PostalCode
ex: 
  person1: 
    name: aaa
    addresses: 
      na: jiang
      sb: su
  person2: 
    name: bbb
    addresses: 
      to: jiang
      bit: su

          